#!/bin/bash

set -euo pipefail
IFS=

spamham="$1"
shift

base=$(dirname "$0")
source "$base"/_spamc.bash

echo "Learning as $spamham:"

for f in "$@"; do 
    echo -n "$f: "
    cat "$f" | _spamc -L "$spamham"
done

echo Ok.
